# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['wins']},
        ),
        migrations.AddField(
            model_name='users',
            name='actcode',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='users',
            name='key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
