# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20170202_2247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set([('name', 'email')]),
        ),
    ]
