# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20170203_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set([]),
        ),
    ]
