# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20170206_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='canrook',
            field=models.BooleanField(default=1, max_length=1),
        ),
    ]
