# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_users_canrook'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='opcanrook',
            field=models.BooleanField(default=1, max_length=1),
        ),
    ]
